edition = "2023";

package nokku.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

service SSOService {
  rpc GetOIDCProvider(GetOIDCProviderRequest) returns (GetOIDCProviderResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (google.api.http) = {get: "/v1/workspaces/{workspace_id}/oidc"};
  }
  rpc UpdateOIDCProvider(UpdateOIDCProviderRequest) returns (UpdateOIDCProviderResponse) {
    option (google.api.http) = {
      patch: "/v1/workspaces/{workspace_id}/oidc"
      body: "*"
    };
  }
  rpc GetSAMLProvider(GetSAMLProviderRequest) returns (GetSAMLProviderResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (google.api.http) = {get: "/v1/workspaces/{workspace_id}/saml"};
  }
  rpc UpdateSAMLProvider(UpdateSAMLProviderRequest) returns (UpdateSAMLProviderResponse) {
    option (google.api.http) = {
      patch: "/v1/workspaces/{workspace_id}/saml"
      body: "*"
    };
  }
}

// OIDC messages --------------------------------------------------------------

message OIDCProvider {
  string workspace_id = 1;
  string name = 2;
  string issuer_url = 3;
  string client_id = 4;
  repeated string scopes = 5;
  bool enforce_sso = 6;
  bool allow_jit_provisioning = 7;
  bool is_active = 8;
  google.protobuf.Timestamp created_at = 9;
  google.protobuf.Timestamp updated_at = 10;
}

message GetOIDCProviderRequest {
  string workspace_id = 1 [(buf.validate.field).string.uuid = true];
}
message GetOIDCProviderResponse {
  OIDCProvider oidc_provider = 1;
}

message UpdateOIDCProviderRequest {
  string workspace_id = 1 [(buf.validate.field).string.uuid = true];
  string name = 2 [(buf.validate.field).string = {
    min_len: 1
    max_len: 256
  }];
  string issuer_url = 3 [(buf.validate.field).string = {
    uri: true
    // prefix: "https://" // TODO: Must be HTTPS
  }];
  string client_id = 4 [(buf.validate.field).string = {
    min_len: 1
    max_len: 500
  }];
  string client_secret = 5 [(buf.validate.field).string = {
    min_len: 1
    max_len: 1000
  }];
  repeated string scopes = 6 [(buf.validate.field).repeated = {
    min_items: 1
    max_items: 20
    items: {
      string: {
        min_len: 1
        max_len: 100
      }
    }
  }];
  bool enforce_sso = 7;
  bool allow_jit_provisioning = 8;
  bool is_active = 9;
}
message UpdateOIDCProviderResponse {
  OIDCProvider oidc_provider = 1;
}

// SAML messages --------------------------------------------------------------

message SAMLProvider {
  string workspace_id = 1;
  string name = 2;
  string metadata_url = 3;
  bool enforce_sso = 4;
  bool allow_jit_provisioning = 5;
  bool is_active = 6;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp updated_at = 8;
}

message GetSAMLProviderRequest {
  string workspace_id = 1 [(buf.validate.field).string.uuid = true];
}
message GetSAMLProviderResponse {
  SAMLProvider saml_provider = 1;
}

message UpdateSAMLProviderRequest {
  string workspace_id = 1 [(buf.validate.field).string.uuid = true];
  string name = 2 [(buf.validate.field).string = {
    min_len: 1
    max_len: 256
  }];
  string metadata_url = 3 [(buf.validate.field).string = {
    uri: true
    // prefix: "https://" // TODO: Must be HTTPS
  }];
  bool enforce_sso = 4;
  bool allow_jit_provisioning = 5;
  bool is_active = 6;
}
message UpdateSAMLProviderResponse {
  SAMLProvider saml_provider = 1;
}
