name: Buf

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: bufbuild/buf-action@8c6a16e16f12ba20b6470afa9c2ba9b5ba8c97c3 # v1
        with:
          setup_only: true
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "go.mod"

      - working-directory: nokku
        run: buf format -d --exit-code

      - working-directory: nokku
        run: buf lint

      - name: Generated code is up to date
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest
          buf generate
          go mod tidy
          go build ./...
          git diff --exit-code
